# Generated by Django 4.2.7 on 2023-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paysilps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Basic_Pay', models.IntegerField()),
                ('Medical_Allowance', models.IntegerField()),
                ('Houseing_Allowance', models.IntegerField()),
                ('Conveyance_Allowance', models.IntegerField()),
                ('Food_Allowance', models.IntegerField()),
                ('National_Insurance', models.IntegerField()),
                ('Loss_of_Pay', models.IntegerField()),
                ('Loan_Repayment', models.IntegerField()),
                ('Advance_Repayment', models.IntegerField()),
                ('Bank', models.CharField(max_length=100)),
                ('Bank_Account', models.BigIntegerField()),
            ],
        ),
    ]
