# Generated by Django 4.2.7 on 2023-11-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Mobile', models.BigIntegerField()),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
    ]
