# Generated by Django 4.2.7 on 2023-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='First_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
