# Generated by Django 4.2.7 on 2023-11-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_details_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_Pay', models.IntegerField()),
                ('Medical_Allowance', models.IntegerField()),
                ('Houseing_Allowance', models.IntegerField()),
                ('Conveyance_Allowance', models.IntegerField()),
                ('Food_Allowance', models.IntegerField()),
                ('Overtime_Allowance', models.IntegerField()),
                ('National_Insurance', models.IntegerField()),
                ('Loss_of_Pay', models.IntegerField()),
                ('Loan_Repayment', models.IntegerField()),
                ('Advance_Repayment', models.IntegerField()),
            ],
        ),
    ]
