# Generated by Django 4.2.7 on 2023-11-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_payslips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslips',
        ),
    ]
